#!/usr/bin/env bash
# Generate odools.toml — the config of the Odoo Language Server used by the
# official Odoo VS Code extension (Odoo.odoo) — from odoo.conf's addons_path,
# so go-to-definition, references and completion resolve across all addons.
#
# odoo.conf is the single source of truth: re-run after editing addons_path
# (`devbox run odools`, or the "Odoo LS: regenerate odools.toml" VS Code task).
# The file holds absolute, machine-specific paths and is git-ignored.
#
# A hand-written odools.toml (without the generated header) is left alone.
set -euo pipefail

WORKSPACE="${PWD}"
CONF="${WORKSPACE}/odoo.conf"
OUT="${WORKSPACE}/odools.toml"
# The project name the template was generated with: main.code-workspace
# selects this profile by that name (Odoo.selectedProfile). The directory
# name only when there is no .copier-answers.yml.
PROFILE="$(awk -F': *' '/^project_name:/ {gsub(/["\x27]/, "", $2); print $2; exit}' \
  "${WORKSPACE}/.copier-answers.yml" 2>/dev/null || true)"
PROFILE="${PROFILE:-$(basename "${WORKSPACE}")}"

HEADER="# GENERATED by scripts/write-odools-toml.sh from odoo.conf — DO NOT EDIT BY HAND, regenerated."

if [ -f "${OUT}" ] && [ "$(head -n1 "${OUT}")" != "${HEADER}" ]; then
  echo "[odools] ${OUT} was not generated by this script — leaving it alone." >&2
  echo "[odools] Remove it and re-run to generate it from odoo.conf." >&2
  exit 0
fi

if [ ! -f "${CONF}" ]; then
  echo "[odools] odoo.conf not found at ${CONF} — skipping."
  exit 0
fi

ADDONS_PATH="$(awk -F= '
  /^[[:space:]]*addons_path[[:space:]]*=/ {
    sub(/^[[:space:]]+/, "", $2)
    print $2
    exit
  }' "${CONF}")"

# Odoo's own addons (odoo/addons, odoo/odoo/addons) are found via odoo_path.
paths=()
IFS=',' read -ra ENTRIES <<< "${ADDONS_PATH}"
for entry in "${ENTRIES[@]}"; do
  entry="$(printf '%s' "$entry" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e 's:/*$::')"
  [ -z "$entry" ] && continue

  if [[ "$entry" = /* ]]; then dir="$entry"; else dir="${WORKSPACE}/${entry}"; fi
  case "$dir" in "${WORKSPACE}/odoo"|"${WORKSPACE}/odoo/"*) continue ;; esac

  if [ ! -d "$dir" ]; then
    echo "[odools] WARNING: addons_path entry '${entry}' does not exist — skipped." >&2
    continue
  fi
  paths+=("$dir")
done

tmp="$(mktemp)"
{
  echo "${HEADER}"
  echo "# Odoo Language Server config: https://github.com/odoo/odoo-ls"
  echo ""
  echo "[[config]]"
  echo "name = \"${PROFILE}\""
  echo "odoo_path = \"${WORKSPACE}/odoo\""
  echo "python_path = \"${WORKSPACE}/.venv/bin/python\""
  echo "addons_paths = ["
  for p in ${paths[@]+"${paths[@]}"}; do
    echo "    \"${p}\","
  done
  echo "]"
} > "${tmp}"
mv "${tmp}" "${OUT}"

echo "[odools] Wrote ${OUT} (profile '${PROFILE}', ${#paths[@]} addons path(s))."
echo "[odools] In VS Code, select profile '${PROFILE}' in the Odoo status bar item if prompted."
